CREATE DATABASE file_upload_db;

CREATE TABLE files (
 id INT NOT NULL AUTO_INCREMENT,
 filename VARCHAR(200) NOT NULL,
 type VARCHAR(30) NOT NULL,
 size INT NOT NULL DEFAULT 0,
 path VARCHAR(200) NOT NULL,
 PRIMARY KEY (id)
);